name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: build for dotnet ${{ matrix.dotnet-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet-version: ['6.0.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with: 
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Build
      run: |
        cd Twitter-Bot/Twitter-Bot
        dotnet build -p:PublishSingleFile=true --self-contained false -c Release
    - name: Test
      run: |
        cd Twitter-Bot/Twitter-Bot
        dotnet test --no-build --verbosity normal
